"""Interoperability bridge for the EaSIeR systems immunology framework."""

from __future__ import annotations

from pathlib import Path
import polars as pl
from returns.result import Failure, Result, Success

from ..schemas import MultiOmicCohort, PredictionResult
from ..types import PredictorCategory


def export_cohort_for_easier(
    cohort: MultiOmicCohort,
    output_dir: Path,
) -> Result[Path, str]:
    """Export cohort expression and metadata to Parquet for EaSIeR R processing."""
    try:
        output_dir.mkdir(parents=True, exist_ok=True)
        expr_path = output_dir / f"{cohort.cohort_id}_easier_expr.parquet"
        cohort.expression_tpm.write_parquet(expr_path)
        return Success(expr_path)
    except Exception as exc:
        return Failure(f"Failed to export cohort for EaSIeR: {exc}")


def load_easier_predictions(
    predictions_csv_path: Path,
    cohort_id: str,
) -> Result[PredictionResult, str]:
    """Load predictions generated by EaSIeR in R."""
    if not predictions_csv_path.exists():
        return Failure(f"EaSIeR predictions file not found: {predictions_csv_path}")

    try:
        df = pl.read_csv(predictions_csv_path)
        sample_col = df.columns[0]
        score_col = next((c for c in df.columns if any(k in c.lower() for k in ("score", "pred", "response", "prob"))), df.columns[1])

        clean_df = df.select([
            pl.col(sample_col).cast(pl.String).alias("sample_id"),
            pl.col(score_col).cast(pl.Float64).alias("score"),
        ])

        return Success(
            PredictionResult(
                predictor_name="EaSIeR",
                category=PredictorCategory.SYSTEMS_MODEL,
                predictions=clean_df,
            )
        )
    except Exception as exc:
        return Failure(f"Failed to parse EaSIeR predictions: {exc}")
