= 4. Discussion

Integrating single-cell deconvolution with subclonal variant dynamics, somatic driver alterations, and single-cell graph differential abundance establishes a coherent multi-dimensional framework aligning with contemporary immunogenomics paradigms @addala2024computational. While deconvolution yields stable cell fraction estimates across untreated cohorts, our observed generalization gap (26.34% classification accuracy) highlights how treatment-naive primary profiles fail to capture heavily pre-treated, metastatic microenvironments. Biologically, prior systemic therapies induce extensive remodeling, stromal activation, and microenvironmental selection. Technically, core needle biopsies from visceral metastases introduce non-trivial purity variations and spatial sampling biases absent in primary surgical resections @addala2024computational.

Crucially, our systematic benchmarking of single-cell neighborhood DA (Milo) versus pseudobulk deconvolution provides actionable rules of engagement for clinical trial design @dann2022differential, @chu2022cell. In surgical resection specimens with balanced cell volumes, high tumor purity, and stable lineage profiles, bulk RNA-seq deconvolution achieves high concordance with single-cell ground truth (Spearman $rho = 0.853$ in Sade-Feldman melanoma), correctly resolving key effector biomarkers such as tertiary lymphoid naive B cells and immunosuppressive macrophages. However, in core needle biopsy scenarios characterized by low cellular yields ($<200$ cells), heavy unmodeled parenchymal contamination ($>60\%$), or substantial cell size asymmetry (macrophages and plasma cells yielding up to $50times$ the mRNA mass of lymphocytes), deconvolution breaks down catastrophically ($rho$ falling to $+0.271$ and sign concordance falling to a $52.5\%$ coin-flip). Furthermore, our discovery that patient-specific marker dysregulation drives deconvolution correlation below zero ($rho = -0.043$) highlights a major vulnerability of static reference matrices. In such clinically challenging contexts, single-cell or high-resolution spatial profiling is strictly mandatory to prevent spurious or directionally inverted biomarker discoveries.

Our subclonal VAF modeling directly addresses intratumor heterogeneity (ITH) as a fundamental determinant of checkpoint response @addala2024computational. The fact that the optimal VAF threshold for TMB varies substantially across indications (VAF = 0.05 in bladder vs. 0.03 in melanoma vs. 0.42 in pancreatic carcinoma) confirms that the immunological relevance of clonal versus subclonal mutations is disease-specific. Clonal neoantigens present across all neoplastic cells stimulate coordinated, persistent T-cell surveillance, whereas subclonal mutations frequently undergo immunoediting or immune evasion. Automated, unsupervised KDE valley detection accurately approximates empirical optimal thresholds, eliminating the risk of overfitting clinical cutoffs.

Furthermore, the predictive utility of the TMB Reliability Score (TRS) and the poor performance of bulk Expressed RNA-TMB demonstrate that bulk transcriptomics lacks the granular sensitivity to model cell-surface neoantigen presentation @addala2024computational. Beyond bulk deconvolution, high-dimensional biomarker discovery directly on bulk expression profiles is severely confounded by sample variance and collinearity. Our finite-sample controlled stability selection across 12 clinical cohorts ($n=1,015$) demonstrates that dynamic regularization budgeting effectively quenches false discovery inflation, maintaining rigorous per-family error bounds ($"PFER" <= 2.5$). The cross-paradigm evaluation of 13 machine learning and econometric fitters established _CXCL13_ as an invariant, model-agnostic driver of response across 12 of 13 algorithms. Furthermore, by projecting out study-level indicator subspaces, Frisch-Waugh-Lovell partialled Lasso (`LassoFWL`) confirmed that core immune infiltration signals persist after purging inter-cohort batch effects. Integrating Ordered Weighted $ell_1$ penalties (OSCAR and SLOPE) resolved collinear multi-gene modules through data-driven octagonal grouping and exact false discovery rate adaptation, offering an optimal mathematical synthesis for multi-omic biomarker prioritization. Finally, the potent association of _TGM6_ alterations with response in melanoma—independent of RNA expression—exemplifies the need to integrate discrete somatic mutations alongside continuous cell infiltration metrics. Future biomarker pipelines should couple high-resolution single-cell deconvolution with clonality-aware mutation scoring, robust stability selection, and HLA loss-of-heterozygosity analysis to achieve robust prospective patient stratification.
